apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-agent-config
  namespace: default
data:
  datadog.yaml: |
    api_key: ${DD_API_KEY}
    site: datadoghq.com
    logs_enabled: true
    apm_config:
      enabled: true
